# NumPy --> Numerical Python 
* Mainly works with array
* Creation, manipulation, reshaping and resizing the array are the most common usage of the NumPy library
* Integer and floats are the main data types - string datatype are not primary datatype in numpy
* Default datatype for numpy is always float
* NumPy array is also called as ndarray ---> N dimensional array
* Numpy array is always homogenous --> It will store only one type of data inside it.

## Array Creation

In [1]:
import numpy as np

In [2]:
ls = [5, 9, 2, 1, 7, 8]

In [3]:
arr1 = np.array(ls)
arr1

array([5, 9, 2, 1, 7, 8])

In [4]:
arr2 = np.array([7, 2, 4, 5, 1, 3])
arr2

array([7, 2, 4, 5, 1, 3])

In [5]:
arr3 = np.array(("Ram", "Sham", "Sita", "Gita", "Ramesh", "Suresh"))
arr3

array(['Ram', 'Sham', 'Sita', 'Gita', 'Ramesh', 'Suresh'], dtype='<U6')

In [6]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr5 = np.arange(5, 19, 3)
arr5

array([ 5,  8, 11, 14, 17])

In [8]:
arr6 = np.linspace(1, 10, 17)
arr6

array([ 1.    ,  1.5625,  2.125 ,  2.6875,  3.25  ,  3.8125,  4.375 ,
        4.9375,  5.5   ,  6.0625,  6.625 ,  7.1875,  7.75  ,  8.3125,
        8.875 ,  9.4375, 10.    ])

In [9]:
arr7 = np.linspace(-4, 3, 9)
arr7

array([-4.   , -3.125, -2.25 , -1.375, -0.5  ,  0.375,  1.25 ,  2.125,
        3.   ])

## Array Information

In [10]:
arr7

array([-4.   , -3.125, -2.25 , -1.375, -0.5  ,  0.375,  1.25 ,  2.125,
        3.   ])

In [11]:
arr7.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
arr3.dtype

dtype('<U6')

In [14]:
type(arr7)

numpy.ndarray

In [15]:
arr2.shape

(6,)

In [16]:
arr6.shape

(17,)

In [17]:
arr6.size

17

## Random Function in Python

In [18]:
arr8 = np.random.rand()   # Will return only one number between zero to one
arr8

0.0731272673702753

In [19]:
arr9 = np.random.rand(15)
arr9

array([0.4921015 , 0.08832213, 0.8249569 , 0.88498387, 0.97924749,
       0.02924217, 0.5194413 , 0.75329927, 0.36162796, 0.41998819,
       0.70398953, 0.64399865, 0.0940672 , 0.93011802, 0.00945355])

In [20]:
arr10 = np.random.randn()   # Will return the normal number where the mean of data will be 0 and std will be 1
arr10

0.2334979291177807

In [21]:
arr10 = np.random.randn(15)
arr10

array([-1.18139167, -1.17930635,  0.10545649,  0.76023611, -0.66730813,
       -0.66442232,  0.90423556,  0.3514723 , -0.82842742, -0.39197646,
       -1.03427129,  0.65304257, -0.50760361, -1.16071645,  0.89257108])

In [22]:
arr11 = np.random.randint(30)
arr11

26

In [23]:
arr12 = np.random.randint(4, 9)
arr12

4

In [24]:
arr13 = np.random.randint(12, 60, 10)
arr13

array([58, 24, 28, 45, 49, 24, 58, 22, 49, 35])

In [25]:
avg_height = 165
std_height = 9

height_100_people = np.random.normal(avg_height, std_height, 100)
height_100_people

array([176.98220143, 161.73645432, 151.90423444, 172.97158706,
       175.92914297, 169.9820579 , 169.55346567, 175.21255774,
       175.81189353, 187.84940571, 159.83162432, 167.95016934,
       162.18339231, 158.16381697, 180.78289559, 151.3230258 ,
       162.92919763, 173.41532929, 159.55752971, 159.69157475,
       153.25605809, 168.25367764, 148.84657034, 169.11328256,
       160.89451004, 171.78942407, 161.53091493, 153.9705481 ,
       173.73065673, 149.66071874, 173.92342728, 177.41091055,
       170.99208042, 171.84227394, 165.17951582, 167.42067522,
       183.33214007, 165.37283727, 167.89951158, 153.95227852,
       168.75185707, 157.23762843, 161.87553114, 171.73858023,
       164.35836078, 164.95329046, 183.81945458, 173.06874876,
       174.0589369 , 168.28989453, 164.11700216, 171.01647978,
       167.05760105, 173.05544115, 165.43952587, 162.27714715,
       185.84731381, 171.71314908, 157.24538638, 153.96754538,
       169.6331103 , 170.52307549, 163.86139416, 172.47

In [26]:
# Finding how many time 5 will occure on top of the dice if dice rolls 10 time.

five_on_top = np.random.binomial(10, (1/6), 20)
five_on_top

array([2, 3, 2, 3, 1, 6, 0, 0, 0, 2, 2, 0, 2, 1, 3, 2, 1, 1, 1, 0])

In [27]:
# Findig how many time head(1) will occur while tossing a coin in 5 iterations

head_on_top = np.random.binomial(1, (1/2), 5)
head_on_top

array([0, 1, 1, 0, 0])

In [28]:
arr3

array(['Ram', 'Sham', 'Sita', 'Gita', 'Ramesh', 'Suresh'], dtype='<U6')

In [29]:
random_name = np.random.choice(arr3, 3)
random_name

array(['Sham', 'Sham', 'Gita'], dtype='<U6')

## Array Resize and Reshape

In [30]:
arr14 = np.random.randint(4, 15, 24)
arr14

array([ 8, 10,  7,  9, 13, 14,  4,  8,  9,  6, 13,  7, 14,  5,  4, 11,  8,
        9, 12,  9, 12,  5, 11, 14])

In [31]:
arr14.shape

(24,)

In [32]:
arr14.reshape(6, 4)

array([[ 8, 10,  7,  9],
       [13, 14,  4,  8],
       [ 9,  6, 13,  7],
       [14,  5,  4, 11],
       [ 8,  9, 12,  9],
       [12,  5, 11, 14]])

In [33]:
arr14.reshape(3, 8)

array([[ 8, 10,  7,  9, 13, 14,  4,  8],
       [ 9,  6, 13,  7, 14,  5,  4, 11],
       [ 8,  9, 12,  9, 12,  5, 11, 14]])

In [34]:
arr14.reshape(12, 2)

array([[ 8, 10],
       [ 7,  9],
       [13, 14],
       [ 4,  8],
       [ 9,  6],
       [13,  7],
       [14,  5],
       [ 4, 11],
       [ 8,  9],
       [12,  9],
       [12,  5],
       [11, 14]])

In [35]:
arr14.reshape(4, 3, 2)

array([[[ 8, 10],
        [ 7,  9],
        [13, 14]],

       [[ 4,  8],
        [ 9,  6],
        [13,  7]],

       [[14,  5],
        [ 4, 11],
        [ 8,  9]],

       [[12,  9],
        [12,  5],
        [11, 14]]])

In [36]:
arr14.reshape(2, 2, 3, 2)

array([[[[ 8, 10],
         [ 7,  9],
         [13, 14]],

        [[ 4,  8],
         [ 9,  6],
         [13,  7]]],


       [[[14,  5],
         [ 4, 11],
         [ 8,  9]],

        [[12,  9],
         [12,  5],
         [11, 14]]]])

In [37]:
arr14

array([ 8, 10,  7,  9, 13, 14,  4,  8,  9,  6, 13,  7, 14,  5,  4, 11,  8,
        9, 12,  9, 12,  5, 11, 14])

In [38]:
arr14.resize(4, 6)

In [39]:
arr14

array([[ 8, 10,  7,  9, 13, 14],
       [ 4,  8,  9,  6, 13,  7],
       [14,  5,  4, 11,  8,  9],
       [12,  9, 12,  5, 11, 14]])

In [40]:
arr14.resize(3, 8)

In [41]:
arr14

array([[ 8, 10,  7,  9, 13, 14,  4,  8],
       [ 9,  6, 13,  7, 14,  5,  4, 11],
       [ 8,  9, 12,  9, 12,  5, 11, 14]])

In [42]:
arr14.shape

(3, 8)

In [43]:
arr14.size

24

In [44]:
arr14.resize(3, 2, 2, 2)

In [45]:
arr14

array([[[[ 8, 10],
         [ 7,  9]],

        [[13, 14],
         [ 4,  8]]],


       [[[ 9,  6],
         [13,  7]],

        [[14,  5],
         [ 4, 11]]],


       [[[ 8,  9],
         [12,  9]],

        [[12,  5],
         [11, 14]]]])

In [46]:
arr14.shape

(3, 2, 2, 2)

In [47]:
arr14.size

24

In [48]:
arr14

array([[[[ 8, 10],
         [ 7,  9]],

        [[13, 14],
         [ 4,  8]]],


       [[[ 9,  6],
         [13,  7]],

        [[14,  5],
         [ 4, 11]]],


       [[[ 8,  9],
         [12,  9]],

        [[12,  5],
         [11, 14]]]])

In [49]:
arr14.reshape(1, 24)

array([[ 8, 10,  7,  9, 13, 14,  4,  8,  9,  6, 13,  7, 14,  5,  4, 11,
         8,  9, 12,  9, 12,  5, 11, 14]])

In [50]:
arr14.ravel()

array([ 8, 10,  7,  9, 13, 14,  4,  8,  9,  6, 13,  7, 14,  5,  4, 11,  8,
        9, 12,  9, 12,  5, 11, 14])

## Numpy array mathematical operation

In [51]:
a = np.array([[2, 6], [-3, 1]])
b = np.array([[9, 3], [-1, -8]])
a, b

(array([[ 2,  6],
        [-3,  1]]),
 array([[ 9,  3],
        [-1, -8]]))

In [52]:
a + b

array([[11,  9],
       [-4, -7]])

In [53]:
a - b

array([[-7,  3],
       [-2,  9]])

In [54]:
a * b

array([[18, 18],
       [ 3, -8]])

In [55]:
a

array([[ 2,  6],
       [-3,  1]])

In [56]:
a + 10

array([[12, 16],
       [ 7, 11]])

In [57]:
a - 3

array([[-1,  3],
       [-6, -2]])

In [58]:
a / b

array([[ 0.22222222,  2.        ],
       [ 3.        , -0.125     ]])

## Statistical Operations on Array

In [59]:
arr15 =  np.random.randint(1, 99, 20).reshape(4, 5)
arr15

array([[39,  1, 68, 35, 90],
       [41, 61, 94, 63, 77],
       [39, 49, 29, 43, 68],
       [22, 73, 25, 67, 45]])

In [60]:
arr15.mean()

51.45

In [61]:
arr15.std()

23.29479555608935

In [62]:
arr15.min()

1

In [63]:
arr15.max()

94

In [64]:
np.median(arr15)

47.0

In [65]:
b

array([[ 9,  3],
       [-1, -8]])

In [66]:
np.abs(b)

array([[9, 3],
       [1, 8]])

In [67]:
height_100_people

array([176.98220143, 161.73645432, 151.90423444, 172.97158706,
       175.92914297, 169.9820579 , 169.55346567, 175.21255774,
       175.81189353, 187.84940571, 159.83162432, 167.95016934,
       162.18339231, 158.16381697, 180.78289559, 151.3230258 ,
       162.92919763, 173.41532929, 159.55752971, 159.69157475,
       153.25605809, 168.25367764, 148.84657034, 169.11328256,
       160.89451004, 171.78942407, 161.53091493, 153.9705481 ,
       173.73065673, 149.66071874, 173.92342728, 177.41091055,
       170.99208042, 171.84227394, 165.17951582, 167.42067522,
       183.33214007, 165.37283727, 167.89951158, 153.95227852,
       168.75185707, 157.23762843, 161.87553114, 171.73858023,
       164.35836078, 164.95329046, 183.81945458, 173.06874876,
       174.0589369 , 168.28989453, 164.11700216, 171.01647978,
       167.05760105, 173.05544115, 165.43952587, 162.27714715,
       185.84731381, 171.71314908, 157.24538638, 153.96754538,
       169.6331103 , 170.52307549, 163.86139416, 172.47

In [68]:
np.round(height_100_people, decimals=2)

array([176.98, 161.74, 151.9 , 172.97, 175.93, 169.98, 169.55, 175.21,
       175.81, 187.85, 159.83, 167.95, 162.18, 158.16, 180.78, 151.32,
       162.93, 173.42, 159.56, 159.69, 153.26, 168.25, 148.85, 169.11,
       160.89, 171.79, 161.53, 153.97, 173.73, 149.66, 173.92, 177.41,
       170.99, 171.84, 165.18, 167.42, 183.33, 165.37, 167.9 , 153.95,
       168.75, 157.24, 161.88, 171.74, 164.36, 164.95, 183.82, 173.07,
       174.06, 168.29, 164.12, 171.02, 167.06, 173.06, 165.44, 162.28,
       185.85, 171.71, 157.25, 153.97, 169.63, 170.52, 163.86, 172.48,
       172.55, 162.65, 152.6 , 161.36, 167.8 , 168.5 , 168.74, 162.04,
       168.09, 164.84, 176.94, 164.41, 159.79, 146.17, 180.28, 167.05,
       162.45, 174.28, 156.77, 168.33, 176.91, 165.27, 174.44, 168.  ,
       169.48, 178.12, 173.98, 164.82, 175.29, 168.88, 160.82, 163.49,
       147.75, 156.41, 165.09, 145.33])

In [69]:
arr15

array([[39,  1, 68, 35, 90],
       [41, 61, 94, 63, 77],
       [39, 49, 29, 43, 68],
       [22, 73, 25, 67, 45]])

In [70]:
np.mean(arr15, axis=1)

array([46.6, 67.2, 45.6, 46.4])

In [71]:
np.mean(arr15, axis=0)

array([35.25, 46.  , 54.  , 52.  , 70.  ])

In [72]:
np.sum(arr15)

1029

In [73]:
np.sum(arr15, axis=1)

array([233, 336, 228, 232])

In [74]:
np.sum(arr15, axis=0)

array([141, 184, 216, 208, 280])

In [75]:
arr1

array([5, 9, 2, 1, 7, 8])

In [76]:
np.append(arr1, 10)

array([ 5,  9,  2,  1,  7,  8, 10])

In [77]:
np.append(arr15, 10)

array([39,  1, 68, 35, 90, 41, 61, 94, 63, 77, 39, 49, 29, 43, 68, 22, 73,
       25, 67, 45, 10])

In [78]:
arr15

array([[39,  1, 68, 35, 90],
       [41, 61, 94, 63, 77],
       [39, 49, 29, 43, 68],
       [22, 73, 25, 67, 45]])

In [79]:
np.append(arr15, [[10],[10],[10],[10]], axis=1)

array([[39,  1, 68, 35, 90, 10],
       [41, 61, 94, 63, 77, 10],
       [39, 49, 29, 43, 68, 10],
       [22, 73, 25, 67, 45, 10]])

In [80]:
np.append(arr15, [[10, 10, 10, 10, 10]], axis=0)

array([[39,  1, 68, 35, 90],
       [41, 61, 94, 63, 77],
       [39, 49, 29, 43, 68],
       [22, 73, 25, 67, 45],
       [10, 10, 10, 10, 10]])

In [83]:
data_from_file = np.loadtxt("demo.csv", delimiter=",", dtype=int)

In [84]:
data_from_file

array([[12,  4, 83, 53],
       [85, 21,  9, -1],
       [93, 45, 14,  8]])

In [92]:
data_from_file2 = np.genfromtxt("demo2.csv", delimiter=",", dtype=int, filling_values=0)

In [93]:
data_from_file2

array([[12,  4, 83, 53],
       [85,  0,  9, -1],
       [93, 45, 14,  8]])

In [94]:
arr15

array([[39,  1, 68, 35, 90],
       [41, 61, 94, 63, 77],
       [39, 49, 29, 43, 68],
       [22, 73, 25, 67, 45]])

In [98]:
np.savetxt("data_from_numpy.csv", arr15,  delimiter=",", fmt="%d")

In [99]:
np.save("numpy_data.np", arr15)

In [101]:
np.load("numpy_data.np.npy")

array([[39,  1, 68, 35, 90],
       [41, 61, 94, 63, 77],
       [39, 49, 29, 43, 68],
       [22, 73, 25, 67, 45]])

In [102]:
p = np.random.randint(1, 10, 12).reshape(3, 4)
p

array([[9, 4, 1, 8],
       [5, 7, 5, 6],
       [8, 1, 4, 3]])

In [103]:
q = np.random.randint(1, 10, 20).reshape(4, 5)
q

array([[9, 3, 1, 9, 1],
       [2, 5, 5, 1, 4],
       [5, 9, 6, 7, 8],
       [7, 5, 9, 8, 5]])

In [104]:
p.dot(q)

array([[150,  96, 107, 156,  73],
       [126, 125, 124, 135, 103],
       [115,  80,  64, 125,  59]])

In [105]:
np.dot(p, q)

array([[150,  96, 107, 156,  73],
       [126, 125, 124, 135, 103],
       [115,  80,  64, 125,  59]])

In [108]:
zero_arr = np.zeros((3, 4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
ones_arr = np.ones((4, 3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [114]:
p

array([[9, 4, 1, 8],
       [5, 7, 5, 6],
       [8, 1, 4, 3]])

In [115]:
p.dot(i)

array([[9., 4., 1., 8.],
       [5., 7., 5., 6.],
       [8., 1., 4., 3.]])

In [118]:
sq = np.random.randint(30, 60, 16).reshape(4, 4)
sq

array([[59, 41, 37, 39],
       [54, 34, 42, 49],
       [34, 44, 45, 49],
       [55, 54, 53, 36]])

In [119]:
sq.trace()

174

In [120]:
sq.T

array([[59, 54, 34, 55],
       [41, 34, 44, 54],
       [37, 42, 45, 53],
       [39, 49, 49, 36]])

In [121]:
p

array([[9, 4, 1, 8],
       [5, 7, 5, 6],
       [8, 1, 4, 3]])

In [122]:
p.T

array([[9, 5, 8],
       [4, 7, 1],
       [1, 5, 4],
       [8, 6, 3]])

In [126]:
mat = np.array([[2, 1], [4, 2]])
mat

array([[2, 1],
       [4, 2]])

In [127]:
np.linalg.det(mat)

0.0

In [124]:
np.linalg.det(sq)

310960.9999999998

In [128]:
np.square(mat)

array([[ 4,  1],
       [16,  4]])

In [129]:
np.sqrt(mat)

array([[1.41421356, 1.        ],
       [2.        , 1.41421356]])

### Create a random number matrix of 16 elements and 1) Reshape in it atleast 3 ways in 2d, 3d format, find its trace value and its Transpose

In [131]:
mat1 = np.random.randint(1, 50, 16)
mat1

array([13, 48, 43, 43, 38, 49, 25, 28,  4, 48, 26, 23, 36, 40, 40, 14])

In [132]:
mat1.reshape(4, 4)

array([[13, 48, 43, 43],
       [38, 49, 25, 28],
       [ 4, 48, 26, 23],
       [36, 40, 40, 14]])

In [133]:
mat1.reshape(8,2)

array([[13, 48],
       [43, 43],
       [38, 49],
       [25, 28],
       [ 4, 48],
       [26, 23],
       [36, 40],
       [40, 14]])

In [134]:
mat1.reshape(2, 4, 2)

array([[[13, 48],
        [43, 43],
        [38, 49],
        [25, 28]],

       [[ 4, 48],
        [26, 23],
        [36, 40],
        [40, 14]]])

In [135]:
mat1.resize(4, 4)

In [136]:
mat1

array([[13, 48, 43, 43],
       [38, 49, 25, 28],
       [ 4, 48, 26, 23],
       [36, 40, 40, 14]])

In [138]:
mat1.trace()

102

In [139]:
mat1.T

array([[13, 38,  4, 36],
       [48, 49, 48, 40],
       [43, 25, 26, 40],
       [43, 28, 23, 14]])

In [140]:
mat1

array([[13, 48, 43, 43],
       [38, 49, 25, 28],
       [ 4, 48, 26, 23],
       [36, 40, 40, 14]])

In [143]:
mat1[2]

array([ 4, 48, 26, 23])

In [144]:
mat1[:,2]

array([43, 25, 26, 40])

In [145]:
mat1[:, -1]

array([43, 28, 23, 14])

In [147]:
mat1[1:3, 1:3]

array([[49, 25],
       [48, 26]])

In [148]:
mat1[1:, 2:]

array([[25, 28],
       [26, 23],
       [40, 14]])

In [149]:
mat1

array([[13, 48, 43, 43],
       [38, 49, 25, 28],
       [ 4, 48, 26, 23],
       [36, 40, 40, 14]])

In [152]:
mat1[:, 0::2]

array([[13, 43],
       [38, 25],
       [ 4, 26],
       [36, 40]])

In [153]:
mat1[0::3, 1:3]

array([[48, 43],
       [40, 40]])

In [156]:
mat1[[0, 2, 3], 2:]

array([[43, 43],
       [26, 23],
       [40, 14]])

In [157]:
arr20 = np.arange(1, 101).reshape(10, 10).T

In [158]:
arr20

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [161]:
arr20[1:3, 3:6]

array([[32, 42, 52],
       [33, 43, 53]])

In [164]:
arr20[[2, 3, 5, 7], 3:]

array([[33, 43, 53, 63, 73, 83, 93],
       [34, 44, 54, 64, 74, 84, 94],
       [36, 46, 56, 66, 76, 86, 96],
       [38, 48, 58, 68, 78, 88, 98]])

In [167]:
arr20[:5:2, 2:7:2]

array([[21, 41, 61],
       [23, 43, 63],
       [25, 45, 65]])

In [170]:
arr20[2::2, [2, 5, 6, 8]]

array([[23, 53, 63, 83],
       [25, 55, 65, 85],
       [27, 57, 67, 87],
       [29, 59, 69, 89]])

In [172]:
np.genfromtxt(r"C:\Users\Soft\Desktop\Py\Docs\demo2.csv", delimiter=",")

array([[12.,  4., 83., 53.],
       [85., nan,  9., -1.],
       [93., 45., 14.,  8.]])